name = "repay-backend"
compatibility_date = "2024-09-23"
# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmNkODM0MTItMjlmMS00NGRlLWI3YjQtNmJhMmU1ZWM1Nzc3IiwidGVuYW50X2lkIjoiNWU4ZGEwMDc4NGUyY2EyMTBhYzZjNmRmZTQwNGVjOTE5MzI4NjVkOGM2NmRlYWJjMWIyZTI5Njc3NDE0ZDgzNyIsImludGVybmFsX3NlY3JldCI6IjZhODgwZmVkLTdmZmItNDBmNi1iYzQ1LTYxOGNlMWZmYmU0OCJ9.4EqYQUBU23QuBBMrDuCfCQ-F_JTU0-MRhXly-t1lsFg"

JWT_SECRET = "myjwtsecret"
